"""initial schema

Revision ID: ec78445a28c5
Revises: 
Create Date: 2026-09-12 08:11:33.218310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movement_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('variant_of', sa.Integer(), nullable=True),
    sa.Column('movement_pattern_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('unilateral', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('compound_or_isolation', sa.Text(), nullable=False),
    sa.Column('tracking_type', sa.Text(), nullable=False),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('cue_notes', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("compound_or_isolation IN ('compound', 'isolation')", name='ck_exercises_compound_or_isolation'),
    sa.CheckConstraint("exercise_type IN ('strength', 'mobility', 'conditioning', 'plyometric', 'stability')", name='ck_exercises_exercise_type'),
    sa.CheckConstraint("tracking_type IN ('reps_weight', 'reps_only', 'time', 'distance', 'time_distance', 'reps_time')", name='ck_exercises_tracking_type'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 6', name='ck_exercises_difficulty'),
    sa.ForeignKeyConstraint(['movement_pattern_id'], ['movement_patterns.id'], ),
    sa.ForeignKeyConstraint(['variant_of'], ['exercises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index('idx_exercises_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('idx_exercises_movement_pattern', ['movement_pattern_id'], unique=False)
        batch_op.create_index('idx_exercises_type', ['exercise_type'], unique=False)
        batch_op.create_index('idx_exercises_variant_of', ['variant_of'], unique=False)

    op.create_table('exercise_equipment',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'equipment_id')
    )
    with op.batch_alter_table('exercise_equipment', schema=None) as batch_op:
        batch_op.create_index('idx_exercise_equipment_equipment', ['equipment_id'], unique=False)

    op.create_table('exercise_muscles',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('primary', 'secondary', 'stabilizer')", name='ck_exercise_muscles_role'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id', 'role')
    )
    with op.batch_alter_table('exercise_muscles', schema=None) as batch_op:
        batch_op.create_index('idx_exercise_muscles_muscle', ['muscle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_muscles', schema=None) as batch_op:
        batch_op.drop_index('idx_exercise_muscles_muscle')

    op.drop_table('exercise_muscles')
    with op.batch_alter_table('exercise_equipment', schema=None) as batch_op:
        batch_op.drop_index('idx_exercise_equipment_equipment')

    op.drop_table('exercise_equipment')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index('idx_exercises_variant_of')
        batch_op.drop_index('idx_exercises_type')
        batch_op.drop_index('idx_exercises_movement_pattern')
        batch_op.drop_index('idx_exercises_difficulty')

    op.drop_table('exercises')
    op.drop_table('muscles')
    op.drop_table('movement_patterns')
    op.drop_table('equipment')
    # ### end Alembic commands ###
