"""workout builder

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-12 08:23:07.587125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_between_rounds_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("block_type IN ('straight_set', 'superset', 'triset', 'circuit', 'emom', 'amrap', 'for_time')", name='ck_workout_blocks_block_type'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'order_index', name='uq_workout_blocks_workout_order')
    )
    with op.batch_alter_table('workout_blocks', schema=None) as batch_op:
        batch_op.create_index('idx_workout_blocks_workout', ['workout_id'], unique=False)

    op.create_table('workout_block_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['workout_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'order_index', name='uq_block_exercises_block_order')
    )
    with op.batch_alter_table('workout_block_exercises', schema=None) as batch_op:
        batch_op.create_index('idx_block_exercises_block', ['block_id'], unique=False)
        batch_op.create_index('idx_block_exercises_exercise', ['exercise_id'], unique=False)

    op.create_table('prescribed_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_block_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('load_value', sa.REAL(), nullable=True),
    sa.Column('load_type', sa.Text(), nullable=True),
    sa.Column('rir_min', sa.Integer(), nullable=True),
    sa.Column('rir_max', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.Text(), nullable=True),
    sa.CheckConstraint("load_type IN ('absolute', 'percent_1rm')", name='ck_prescribed_sets_load_type'),
    sa.ForeignKeyConstraint(['workout_block_exercise_id'], ['workout_block_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_block_exercise_id', 'set_number', name='uq_prescribed_sets_exercise_set')
    )
    with op.batch_alter_table('prescribed_sets', schema=None) as batch_op:
        batch_op.create_index('idx_prescribed_sets_block_exercise', ['workout_block_exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescribed_sets', schema=None) as batch_op:
        batch_op.drop_index('idx_prescribed_sets_block_exercise')

    op.drop_table('prescribed_sets')
    with op.batch_alter_table('workout_block_exercises', schema=None) as batch_op:
        batch_op.drop_index('idx_block_exercises_exercise')
        batch_op.drop_index('idx_block_exercises_block')

    op.drop_table('workout_block_exercises')
    with op.batch_alter_table('workout_blocks', schema=None) as batch_op:
        batch_op.drop_index('idx_workout_blocks_workout')

    op.drop_table('workout_blocks')
    op.drop_table('workouts')
    # ### end Alembic commands ###
