"""program builder

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-12 09:20:09.886776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'paused', 'cancelled')", name='ck_program_assignments_status'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_assignments_program', ['program_id'], unique=False)

    op.create_table('program_weeks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('phase_label', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("phase_label IN ('accumulation', 'intensification', 'deload') OR phase_label IS NULL", name='ck_program_weeks_phase_label'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'week_number', name='uq_program_weeks_program_week')
    )
    with op.batch_alter_table('program_weeks', schema=None) as batch_op:
        batch_op.create_index('idx_program_weeks_program', ['program_id'], unique=False)

    op.create_table('assigned_program_weeks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_assignment_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('phase_label', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("phase_label IN ('accumulation', 'intensification', 'deload') OR phase_label IS NULL", name='ck_assigned_program_weeks_phase_label'),
    sa.ForeignKeyConstraint(['program_assignment_id'], ['program_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_assignment_id', 'week_number', name='uq_assigned_program_weeks_assignment_week')
    )
    with op.batch_alter_table('assigned_program_weeks', schema=None) as batch_op:
        batch_op.create_index('idx_assigned_weeks_assignment', ['program_assignment_id'], unique=False)

    op.create_table('program_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_week_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_week_id'], ['program_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_week_id', 'day_number', name='uq_program_days_week_day')
    )
    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.create_index('idx_program_days_week', ['program_week_id'], unique=False)

    op.create_table('assigned_program_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assigned_program_week_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_program_week_id'], ['assigned_program_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assigned_program_week_id', 'day_number', name='uq_assigned_program_days_week_day')
    )
    with op.batch_alter_table('assigned_program_days', schema=None) as batch_op:
        batch_op.create_index('idx_assigned_days_week', ['assigned_program_week_id'], unique=False)

    op.create_table('program_day_workouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_day_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_day_id', 'order_index', name='uq_program_day_workouts_day_order')
    )
    with op.batch_alter_table('program_day_workouts', schema=None) as batch_op:
        batch_op.create_index('idx_program_day_workouts_day', ['program_day_id'], unique=False)

    op.create_table('assigned_day_workouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assigned_program_day_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_program_day_id'], ['assigned_program_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assigned_program_day_id', 'order_index', name='uq_assigned_day_workouts_day_order')
    )
    with op.batch_alter_table('assigned_day_workouts', schema=None) as batch_op:
        batch_op.create_index('idx_assigned_day_workouts_day', ['assigned_program_day_id'], unique=False)

    op.create_table('session_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assigned_program_day_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_program_day_id'], ['assigned_program_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.create_index('idx_session_logs_day', ['assigned_program_day_id'], unique=False)

    op.create_table('logged_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_log_id', sa.Integer(), nullable=False),
    sa.Column('prescribed_set_id', sa.Integer(), nullable=True),
    sa.Column('workout_block_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_load_value', sa.REAL(), nullable=True),
    sa.Column('actual_load_type', sa.Text(), nullable=True),
    sa.Column('actual_rir', sa.Integer(), nullable=True),
    sa.CheckConstraint("actual_load_type IN ('absolute', 'percent_1rm') OR actual_load_type IS NULL", name='ck_logged_sets_actual_load_type'),
    sa.ForeignKeyConstraint(['prescribed_set_id'], ['prescribed_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_log_id'], ['session_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_block_exercise_id'], ['workout_block_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logged_sets', schema=None) as batch_op:
        batch_op.create_index('idx_logged_sets_prescribed', ['prescribed_set_id'], unique=False)
        batch_op.create_index('idx_logged_sets_session', ['session_log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logged_sets', schema=None) as batch_op:
        batch_op.drop_index('idx_logged_sets_session')
        batch_op.drop_index('idx_logged_sets_prescribed')

    op.drop_table('logged_sets')
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_session_logs_day')

    op.drop_table('session_logs')
    with op.batch_alter_table('assigned_day_workouts', schema=None) as batch_op:
        batch_op.drop_index('idx_assigned_day_workouts_day')

    op.drop_table('assigned_day_workouts')
    with op.batch_alter_table('program_day_workouts', schema=None) as batch_op:
        batch_op.drop_index('idx_program_day_workouts_day')

    op.drop_table('program_day_workouts')
    with op.batch_alter_table('assigned_program_days', schema=None) as batch_op:
        batch_op.drop_index('idx_assigned_days_week')

    op.drop_table('assigned_program_days')
    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.drop_index('idx_program_days_week')

    op.drop_table('program_days')
    with op.batch_alter_table('assigned_program_weeks', schema=None) as batch_op:
        batch_op.drop_index('idx_assigned_weeks_assignment')

    op.drop_table('assigned_program_weeks')
    with op.batch_alter_table('program_weeks', schema=None) as batch_op:
        batch_op.drop_index('idx_program_weeks_program')

    op.drop_table('program_weeks')
    with op.batch_alter_table('program_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_assignments_program')

    op.drop_table('program_assignments')
    op.drop_table('programs')
    # ### end Alembic commands ###
